import localFont from "next/font/local";
import { Andika } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const andika = Andika({
  weight: ["400", "700"], // Make sure this is in an array or a string as per your need
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${andika.className} antialiased overflow-x-hidden `}
      >
        <div
          className="w-full   bg-[#FFF9F9]"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
